### ISSUE TITLE
Directions for interstates

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/STL_GEOCODER_Placename#3]
Hey @bransonf - here are the possibilities:

```
I 70 EASTBOUND
I 70 WESTBOUND
I 64 EASTBOUND
I 64 WESTBOUND
I 55 NORTHBOUND
I 55 SOUTHBOUND
I 44 EASTBOUND
1 44 WESTBOUND
I 70 Eastbound
I 70 Westbound
I 64 Eastbound
I 64 Westbound
I 55 Northbound
I 55 Southbound
I 44 Eastbound
1 44 Westbound
```

**Comment by bransonf** [comment]
So we need to produce (for example):
```
Riverview Dr at I-70 EASTBOUND
Riverview Dr at I-70 Westbound
I-55 Northbound at Riverview Dr
I-55 SOUTBOUND at Riverview Dr
```

Is this correct? These are just suffixes to interstates?

And as far as capitalization goes, is the geocoder currently case sensitive? All of the commercial options are case-insensitive.

**Comment by chris-prener** [comment]
Thanks sorry - we just need `Northbound` not `NORTHBOUND` I meant to delete that
